/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABtn: typeof import('anu-vue')['ABtn']
    ACard: typeof import('anu-vue')['ACard']
    ACheckbox: typeof import('anu-vue')['ACheckbox']
    AInput: typeof import('anu-vue')['AInput']
    AMenu: typeof import('anu-vue')['AMenu']
    ASelect: typeof import('anu-vue')['ASelect']
    ColourPickerMenu: typeof import('./src/components/ColourPickerMenu.vue')['default']
    FilamentColourTypeSelect: typeof import('./src/components/FilamentColourTypeSelect.vue')['default']
    GeneratedLabel: typeof import('./src/components/GeneratedLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
